### ISSUE TITLE
1.1d release is not statically linked...

### ISSUE THREAD

**Issue by rwbc** [nitrocan/sctr#20]
Cannot run elsewhere with missing libraries.

Guenther

**Comment by nitrocan** [comment]
Is this the Windows or the Linux version?

Can

**Comment by nitrocan** [comment]
Please let me know if https://github.com/nitrocan/sctr/releases/tag/1.1e works, thanks!

**Comment by rwbc** [comment]
Yes, of course it works now - and I meant the Win version. Thanks!
I don't understand though why someone opened the same issue 2 days after mine.

Guenther

**Comment by nitrocan** [comment]
A million thanks!
