### ISSUE TITLE
sctr win7 x64 v1.1d

### ISSUE THREAD

**Issue by yellow-panther** [nitrocan/sctr#26]
The following files are missing:
**libgcc_s_seh-1.dll**  https://www.dll-files.com/libgcc_s_seh-1.dll.html 
**libwinthread1-1.dll** https://www.dll-files.com/libwinpthread-1.dll.html

but even after this procedure an application error occurs on my screen: 0xc000007b - program cannot be launched

**Comment by nitrocan** [comment]
Addressing now, thanks for your comment.

**Comment by nitrocan** [comment]
Please let me know if https://github.com/nitrocan/sctr/releases/tag/1.1e works, thanks!
